apiVersion: v1
kind: Service
metadata:
  name: dev-mongodb-lb
  namespace: dev-mongodb
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
