apiVersion: v1
kind: Service
metadata:
  name: hw-nodejs
  labels:
    service: hw-nodejs
spec:
  selector:
    app: hw-nodejs
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
